In [3]:
import os
import pandas as pd
from kaggle.api.kaggle_api_extended import KaggleApi

In [5]:
# Ensure your API key is in ~/.kaggle/kaggle.json
# Je l'ai mis dans  ~/home/thomas_d/.config/kaggle/kaggle.json
api = KaggleApi()
api.authenticate()

# Download the dataset to the 'data' folder
dataset = 'infamouscoder/depression-reddit-cleaned'
download_path = '../../data' #Path à changer au besoin
api.dataset_download_files(dataset, path=download_path, unzip=True)

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/thomas_d/.config/kaggle/kaggle.json'
Dataset URL: https://www.kaggle.com/datasets/infamouscoder/depression-reddit-cleaned

In [7]:
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()
dataset2 = "rishabhkausish/reddit-depression-dataset"
download_path = '../../data' #Path à changer au besoin
api.dataset_download_files(dataset2, path=download_path, unzip=True)

Dataset URL: https://www.kaggle.com/datasets/rishabhkausish/reddit-depression-dataset

In [ ]:
'''import os
#pip install datasets si besoin
from datasets import load_dataset

def download_emotion_dataset(target_dir="data/raw"):
    os.makedirs(target_dir, exist_ok=True)
    print("Downloading dair-ai/emotion dataset from Hugging Face...")
    dataset = load_dataset("emotion")
    for split in dataset:
        out_path = os.path.join(target_dir, f"emotion_{split}.csv")
        dataset[split].to_csv(out_path, index=False)
        print(f"Saved {split} split to {out_path}")dataset'''

In [2]:
import importlib
import os
import sys

sys.path.insert(0, os.path.abspath(".."))

from src.data_cleaning.data import download_data, load_data

In [ ]:
download_data()

Downloading to /home/thomas_d/code/Projet/data/1.archive...

100%|██████████| 431M/431M [00:35<00:00, 12.7MB/s]

Extracting files...

Dataset téléchargé.

/home/thomas_d/code/Projet/mental-health-signal-detector/src/data_cleaning/data.py:28: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/reddit_depression_dataset.csv")

In [24]:
df_test = load_data()

/home/thomas_d/code/Projet/mental-health-signal-detector/src/data_cleaning/data.py:28: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/reddit_depression_dataset.csv")

In [38]:
df_test.isna().sum()

Unnamed: 0           3
subreddit           20
title               23
body            461051
upvotes             64
created_utc        106
num_comments    113977
label              106
dtype: int64

In [52]:
importlib.reload(sys.modules["src.data_cleaning.data"])
from src.data_cleaning.data import clean_data, balance_classes

In [56]:
df_cleaned = clean_data(df_test)

label
0.0    1990260
1.0     480409
Name: count, dtype: int64

In [57]:
df_cleaned["label"].value_counts()

label
0.0    1990260
1.0     480409
Name: count, dtype: int64

In [54]:
df_balanced = balance_classes(df_cleaned, "label")

In [55]:
df_balanced["label"].value_counts()

label
0.0    480409
1.0    480409
Name: count, dtype: int64

In [46]:
df_cleaned.shape

(2470669, 2)

In [47]:
df_cleaned["label"].value_counts()

label
0.0    1990260
1.0     480409
Name: count, dtype: int64

In [29]:
df = pd.read_csv("../../data/reddit_depression_dataset.csv")

/tmp/ipykernel_27589/3234879418.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/reddit_depression_dataset.csv")

In [43]:
df.head(10)

,Unnamed: 0,subreddit,title,body,upvotes,created_utc,num_comments,label
0,47951,DeepThoughts,Deep thoughts underdog,"Only when we start considering ourselves, the ...",4.0,1.405309e+09,NaN,0.0
1,47952,DeepThoughts,"I like this sub, there's only two posts yet I ...",Anyway: Human Morality is a joke so long as th...,4.0,1.410568e+09,1.0,0.0
2,47957,DeepThoughts,Rebirth!,Hello. \nI am the new guy in charge here (Besi...,6.0,1.416458e+09,1.0,0.0
3,47959,DeepThoughts,"""I want to be like water. I want to slip throu...",NaN,25.0,1.416512e+09,2.0,0.0
4,47960,DeepThoughts,Who am I?,You could take any one cell in my body and kil...,5.0,1.416516e+09,4.0,0.0
5,47969,DeepThoughts,What is the limit of the knowledge and power a...,"Personally, I think it's infinite. We will alw...",8.0,1.416684e+09,23.0,0.0
6,47971,DeepThoughts,"Nearly every major conflic, war, and genocide ...",NaN,6.0,1.416824e+09,9.0,0.0
7,47973,DeepThoughts,"10,000 Bits Contest (ChangeTip)","Hello, from now to Christmas we will be hostin...",7.0,1.416870e+09,26.0,0.0
8,47974,DeepThoughts,What is our purpose?,NaN,4.0,1.416871e+09,14.0,0.0
9,47977,DeepThoughts,Just like bacteria live in our gut and are sym...,"Do stars, solar systems, galaxies, all have co...",8.0,1.416898e+09,16.0,0.0

In [22]:
sub_df_test = df_test[["subreddit", "body", "label"]]
sub_df_test.head(10)
df_test.drop(columns=["body"], inplace=True)
df_test.rename(columns={"body": "title"}, inplace=True)
df_cleaned = pd.concat([df_test, sub_df_test], axis=0)
df_cleaned.head()

,Unnamed: 0,subreddit,title,upvotes,created_utc,num_comments,label,body
0,47951,DeepThoughts,Deep thoughts underdog,4.0,1.405309e+09,NaN,0.0,NaN
1,47952,DeepThoughts,"I like this sub, there's only two posts yet I ...",4.0,1.410568e+09,1.0,0.0,NaN
2,47957,DeepThoughts,Rebirth!,6.0,1.416458e+09,1.0,0.0,NaN
3,47959,DeepThoughts,"""I want to be like water. I want to slip throu...",25.0,1.416512e+09,2.0,0.0,NaN
4,47960,DeepThoughts,Who am I?,5.0,1.416516e+09,4.0,0.0,NaN

In [23]:
df_cleaned.shape

(4941556, 8)

In [39]:
df.isna().sum()

Unnamed: 0      0.000008
subreddit       0.000008
title           0.000011
body            0.186602
upvotes         0.000026
created_utc     0.000043
num_comments    0.046130
label           0.000043
dtype: float64

In [12]:
df_test.isna().sum()

Unnamed: 0           3
subreddit           20
title               23
body            461051
upvotes             64
created_utc        106
num_comments    113977
label              106
dtype: int64

In [17]:
df_test.dropna(subset=["Unnamed: 0","subreddit","title",
                       "upvotes", "created_utc", "label"], axis=0)

,Unnamed: 0,subreddit,title,body,upvotes,created_utc,num_comments,label
0,47951,DeepThoughts,Deep thoughts underdog,"Only when we start considering ourselves, the ...",4.0,1.405309e+09,NaN,0.0
1,47952,DeepThoughts,"I like this sub, there's only two posts yet I ...",Anyway: Human Morality is a joke so long as th...,4.0,1.410568e+09,1.0,0.0
2,47957,DeepThoughts,Rebirth!,Hello. \nI am the new guy in charge here (Besi...,6.0,1.416458e+09,1.0,0.0
3,47959,DeepThoughts,"""I want to be like water. I want to slip throu...",NaN,25.0,1.416512e+09,2.0,0.0
4,47960,DeepThoughts,Who am I?,You could take any one cell in my body and kil...,5.0,1.416516e+09,4.0,0.0
...,...,...,...,...,...,...,...,...
2470773,10742224,depression,Alone as usual,I just argued with my mom an hour ago; she alw...,9.0,1.672529e+09,6.0,1.0
2470774,10742230,depression,Help needed urgently!,OK basically non of my friend's or family invi...,5.0,1.672530e+09,7.0,1.0
2470775,10742232,depression,I know what your thinking,Don't do It. Not today. Its gonna be ok if you...,10.0,1.672530e+09,8.0,1.0
2470776,10742243,depression,how do I stop having such a cynical view on ma...,"So I don't know, I've recently realized that t...",8.0,1.672531e+09,9.0,1.0
2470777,10742244,depression,2022 year in review:,It sucked.\n\nGod help us all,13.0,1.672531e+09,2.0,1.0

In [31]:
# 1) Copie de sécurité
df_backup = df.copy(deep=True)

# 2) Détection des lignes inversées :
#    - Unnamed: 0 devrait être numérique
#    - title devrait être du texte
unnamed_is_numeric = pd.to_numeric(df["Unnamed: 0"], errors="coerce").notna()
title_is_numeric = pd.to_numeric(df["title"], errors="coerce").notna()
mask = (~unnamed_is_numeric) & title_is_numeric

# 3) Inversion des valeurs entre les 2 colonnes sur ces lignes
df.loc[mask, ["Unnamed: 0", "title"]] = (
    df.loc[mask, ["title", "Unnamed: 0"]].to_numpy()
)

# 4) Contrôle rapide
print(f"Lignes corrigées: {mask.sum()}")

Lignes corrigées: 42

In [28]:
mask[:10]

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: title, dtype: bool